"""Update search property and listing schemas

Revision ID: 0e38cbef77fd
Revises: 6c658adc28cf
Create Date: 2025-03-05 19:19:36.456704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e38cbef77fd'
down_revision: Union[str, None] = '6c658adc28cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
