"""listing edit

Revision ID: 10c359e9be4e
Revises: 8db33e3d6df5
Create Date: 2025-03-06 13:50:54.441083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c359e9be4e'
down_revision: Union[str, None] = '8db33e3d6df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('location', sa.String(length=255), nullable=False))
    op.drop_column('property_searches', 'city')
    op.drop_column('property_searches', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('property_searches', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('property_searches', 'location')
    # ### end Alembic commands ###
