"""update to listings model and schema

Revision ID: 116d13fd32eb
Revises: d06d17039162
Create Date: 2025-03-04 13:47:09.796188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116d13fd32eb'
down_revision: Union[str, None] = 'd06d17039162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('status_type', sa.String(length=50), nullable=False))
    op.add_column('listings', sa.Column('home_Type', sa.String(length=50), nullable=False))
    op.drop_constraint('listings_agent_id_fkey', 'listings', type_='foreignkey')
    op.drop_column('listings', 'agent_id')
    op.add_column('property_searches', sa.Column('status_type', sa.String(length=50), nullable=False))
    op.add_column('property_searches', sa.Column('home_Type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_searches', 'home_Type')
    op.drop_column('property_searches', 'status_type')
    op.add_column('listings', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('listings_agent_id_fkey', 'listings', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('listings', 'home_Type')
    op.drop_column('listings', 'status_type')
    # ### end Alembic commands ###
