"""listing and lead

Revision ID: 2170a8a90d3f
Revises: e17e2c2f1af1
Create Date: 2025-03-12 18:56:20.026919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2170a8a90d3f'
down_revision: Union[str, None] = 'e17e2c2f1af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listings_lead_id_fkey', 'listings', type_='foreignkey')
    op.drop_column('listings', 'lead_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('listings_lead_id_fkey', 'listings', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
