"""listing and lead

Revision ID: 2c9ccedf3348
Revises: 8da79595a820
Create Date: 2025-03-12 18:22:23.480330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9ccedf3348'
down_revision: Union[str, None] = '8da79595a820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('listings_id_key', 'listings', type_='unique')
    op.drop_column('listings', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('listings_id_key', 'listings', ['id'])
    # ### end Alembic commands ###
