"""Update search property and listing schemas

Revision ID: 2d06ba42be6e
Revises: 550334ea8ba2
Create Date: 2025-03-05 18:57:40.278585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d06ba42be6e'
down_revision: Union[str, None] = '550334ea8ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
