"""Update search property and listing schemas

Revision ID: 351b171ffb92
Revises: e03c12d5c4ef
Create Date: 2025-03-05 17:49:47.038784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351b171ffb92'
down_revision: Union[str, None] = 'e03c12d5c4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
