"""Update search property and listing schemas

Revision ID: 3d56dfc33d3d
Revises: 57f82685bf95
Create Date: 2025-03-05 18:29:41.548084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d56dfc33d3d'
down_revision: Union[str, None] = '57f82685bf95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
