"""Update search property and listing schemas

Revision ID: 550334ea8ba2
Revises: 3d56dfc33d3d
Create Date: 2025-03-05 18:56:26.139831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550334ea8ba2'
down_revision: Union[str, None] = '3d56dfc33d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
