"""Update search property and listing schemas

Revision ID: 57f82685bf95
Revises: ed9eb9dc1d31
Create Date: 2025-03-05 18:19:49.092532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f82685bf95'
down_revision: Union[str, None] = 'ed9eb9dc1d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('days_on_market', sa.Integer(), nullable=False))
    op.drop_column('listings', 'days_on_zillow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('days_on_zillow', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('listings', 'days_on_market')
    # ### end Alembic commands ###
