"""edit to lead model

Revision ID: 5e276737c275
Revises: b4add90a113f
Create Date: 2025-03-11 14:55:10.346328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e276737c275'
down_revision: Union[str, None] = 'b4add90a113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('zpid', sa.Integer(), nullable=False))
    op.drop_constraint('leads_listing_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'listings', ['zpid'], ['zpid'], ondelete='CASCADE')
    op.drop_column('leads', 'listing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_listing_id_fkey', 'leads', 'listings', ['listing_id'], ['zpid'], ondelete='CASCADE')
    op.drop_column('leads', 'zpid')
    # ### end Alembic commands ###
