"""Update search property and listing schemas

Revision ID: 603ef064ea36
Revises: 0e38cbef77fd
Create Date: 2025-03-05 19:33:34.829582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ef064ea36'
down_revision: Union[str, None] = '0e38cbef77fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
