"""Update search property and listing schemas

Revision ID: 6c658adc28cf
Revises: ce64f45db2ca
Create Date: 2025-03-05 19:17:12.096192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c658adc28cf'
down_revision: Union[str, None] = 'ce64f45db2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
