"""Update search property and listing schemas

Revision ID: 7d0f218164f5
Revises: abcdf05d01fe
Create Date: 2025-03-05 13:43:55.280020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0f218164f5'
down_revision: Union[str, None] = 'abcdf05d01fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
