"""property search edit

Revision ID: 8ae1ad793c2d
Revises: 07860d440e77
Create Date: 2025-03-06 14:02:32.815234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae1ad793c2d'
down_revision: Union[str, None] = '07860d440e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('home_type', sa.String(length=50), nullable=False))
    op.drop_column('property_searches', 'home_Type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('home_Type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('property_searches', 'home_type')
    # ### end Alembic commands ###
