"""listing and lead

Revision ID: 8da79595a820
Revises: 
Create Date: 2025-03-12 18:18:32.775240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da79595a820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zpid', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status_type', sa.String(length=50), nullable=False),
    sa.Column('home_type', sa.String(length=50), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('square_ft', sa.Integer(), nullable=False),
    sa.Column('days_on_market', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zpid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('interest_level', sa.String(length=100), nullable=False),
    sa.Column('date_saved', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zpid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zpid'], ['listings.zpid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zpid', name='unique_lead_listing')
    )
    op.create_table('property_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status_type', sa.String(length=50), nullable=False),
    sa.Column('home_type', sa.String(length=50), nullable=False),
    sa.Column('price_min', sa.Integer(), nullable=False),
    sa.Column('price_max', sa.Integer(), nullable=False),
    sa.Column('beds_min', sa.Integer(), nullable=False),
    sa.Column('beds_max', sa.Integer(), nullable=False),
    sa.Column('baths_min', sa.Integer(), nullable=False),
    sa.Column('baths_max', sa.Integer(), nullable=False),
    sa.Column('square_ft_min', sa.Integer(), nullable=False),
    sa.Column('square_ft_max', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['search_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_searches')
    op.drop_table('leads')
    op.drop_table('listings')
    # ### end Alembic commands ###
