"""Update search property and listing schemas

Revision ID: 92a4411f1ebe
Revises: a900d4a6dc87
Create Date: 2025-03-05 17:41:28.232093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a4411f1ebe'
down_revision: Union[str, None] = 'a900d4a6dc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
