"""property search edit

Revision ID: a18c8d4cbce0
Revises: 8ae1ad793c2d
Create Date: 2025-03-06 14:04:32.961142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18c8d4cbce0'
down_revision: Union[str, None] = '8ae1ad793c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('beds_min', sa.Integer(), nullable=False))
    op.add_column('property_searches', sa.Column('beds_max', sa.Integer(), nullable=False))
    op.add_column('property_searches', sa.Column('baths_min', sa.Integer(), nullable=False))
    op.add_column('property_searches', sa.Column('baths_max', sa.Integer(), nullable=False))
    op.drop_column('property_searches', 'beds')
    op.drop_column('property_searches', 'baths')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_searches', sa.Column('baths', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('property_searches', sa.Column('beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('property_searches', 'baths_max')
    op.drop_column('property_searches', 'baths_min')
    op.drop_column('property_searches', 'beds_max')
    op.drop_column('property_searches', 'beds_min')
    # ### end Alembic commands ###
