"""Update search property and listing schemas

Revision ID: a900d4a6dc87
Revises: 9bb1263cb071
Create Date: 2025-03-05 17:32:09.360649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a900d4a6dc87'
down_revision: Union[str, None] = '9bb1263cb071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('bedrooms', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('bathrooms', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('days_on_zillow', sa.Integer(), nullable=False))
    op.drop_column('listings', 'baths')
    op.drop_column('listings', 'beds')
    op.drop_column('listings', 'days_on_market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('days_on_market', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('beds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('baths', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('listings', 'days_on_zillow')
    op.drop_column('listings', 'bathrooms')
    op.drop_column('listings', 'bedrooms')
    # ### end Alembic commands ###
