"""Update search property and listing schemas

Revision ID: ad4ba82ca93a
Revises: c98d6f840e7c
Create Date: 2025-03-05 13:36:41.521070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4ba82ca93a'
down_revision: Union[str, None] = 'c98d6f840e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
