"""Update search property and listing schemas

Revision ID: c98d6f840e7c
Revises: 116d13fd32eb
Create Date: 2025-03-05 13:23:26.449029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98d6f840e7c'
down_revision: Union[str, None] = '116d13fd32eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
