"""Update search property and listing schemas

Revision ID: ce64f45db2ca
Revises: a5ad05468fe9
Create Date: 2025-03-05 19:16:00.649385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce64f45db2ca'
down_revision: Union[str, None] = 'a5ad05468fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('home_type', sa.String(length=50), nullable=False))
    op.drop_column('listings', 'home_Type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('home_Type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('listings', 'home_type')
    # ### end Alembic commands ###
