"""Update search property and listing schemas

Revision ID: e03c12d5c4ef
Revises: 92a4411f1ebe
Create Date: 2025-03-05 17:42:17.163439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03c12d5c4ef'
down_revision: Union[str, None] = '92a4411f1ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
