"""listing and lead

Revision ID: e17e2c2f1af1
Revises: c08c806806b5
Create Date: 2025-03-12 18:52:18.887985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17e2c2f1af1'
down_revision: Union[str, None] = 'c08c806806b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'lead_id')
    # ### end Alembic commands ###
