"""Update search property and listing schemas

Revision ID: ed9eb9dc1d31
Revises: 351b171ffb92
Create Date: 2025-03-05 18:07:50.053915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9eb9dc1d31'
down_revision: Union[str, None] = '351b171ffb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
