"""Update search property and listing schemas

Revision ID: fcc9161ef9f0
Revises: 7d0f218164f5
Create Date: 2025-03-05 13:44:37.595250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc9161ef9f0'
down_revision: Union[str, None] = '7d0f218164f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
